# Generated by Django 5.2.15 on 2026-06-09 08:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(default='Head Chef', max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joined_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ICE_RENT', 'Ice-block rent'), ('SUPPLIES', 'Fish supplies'), ('UTILITIES', 'Utilities'), ('WAGES', 'Wages'), ('OTHER', 'Other')], max_length=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('incurred_on', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-incurred_on'],
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('species', models.CharField(blank=True, max_length=80)),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, help_text='Kilograms currently in stock.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=0, help_text='What Pingu pays the supplier per kg.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('freshness', models.CharField(choices=[('FRESH', 'Fresh'), ('GOOD', 'Good'), ('USE_SOON', 'Use soon')], default='FRESH', max_length=10)),
                ('caught_on', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Fish',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('SERVED', 'Served'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurant.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='One step per line.')),
                ('category', models.CharField(choices=[('APPETIZER', 'Appetizers'), ('MAIN', 'Main Courses'), ('SALAD', 'Salads & Sides'), ('DESSERT', 'Desserts & Sweets'), ('HEALTHY', 'Healthy Eats')], default='MAIN', max_length=12)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner Friendly'), ('INTERMEDIATE', 'Intermediate Level'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=12)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Menu price for customers.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('prep_minutes', models.PositiveIntegerField(default=15)),
                ('cook_minutes', models.PositiveIntegerField(default=10)),
                ('servings', models.PositiveIntegerField(default=2)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='restaurant.chef')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='restaurant.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0.25, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='restaurant.fish')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='restaurant.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'fish')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='restaurant.RecipeIngredient', to='restaurant.fish'),
        ),
        migrations.AddField(
            model_name='fish',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fish_items', to='restaurant.supplier'),
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('APPETIZER', 'Appetizers'), ('MAIN', 'Main Courses'), ('SALAD', 'Salads & Sides'), ('DESSERT', 'Desserts & Sweets'), ('HEALTHY', 'Healthy Eats')], max_length=12)),
                ('score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='restaurant.customer')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('customer', 'category')},
            },
        ),
    ]
